diabetes_prediction_flaskapp/app/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import current_user
from app.models import Patient, User

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
	if current_user.is_authenticated:
		return redirect(url_for('main.view'))
	#page = request.args.get('page', 1, type=int)
	#patient = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	return render_template('index.html', title='Home')


@main.route("/about")
def about():
	return render_template("about.html", title='About')


@main.route("/view")
def view():
	page = request.args.get('page', 1, type=int)
	patients = Patient.query.order_by(Patient.date_posted.desc()).paginate(page=page)
	return render_template('view.html', patients=patients, title='Patients')

diabetes_prediction_flaskapp/app/patients/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint, Markup)
from flask_login import current_user, login_required
from app import db
from app.models import Patient
from app.patients.forms import PatientForm
import pickle
import numpy as np


patients = Blueprint('patients', __name__)


@patients.route("/patient/new", methods=['GET','POST'])
@login_required
def new_patient():
	form = PatientForm()
	if form.validate_on_submit():

		preg = int(form.pregnancies.data)
		gluc = int(form.glucose.data)
		bm = int(form.bmi.data)
		pedigree = int(form.pedigree_function.data)
		ag = int(form.age.data)
		arr = np.array([[preg,gluc,bm,pedigree,ag]])
		#loading model
		loaded_model = pickle.load(open('../second_diabetes_classification_model.sav', 'rb'))
		result = loaded_model.predict(arr)
		
		if result[0] == 1:
			output = 1
			word = "Patient likely to be Diabetic"
		else:
			output = 0
			word = "Patient not Diabetic"

		patient = Patient(pregnancies=form.pregnancies.data, glucose=form.glucose.data, 
							bmi=form.bmi.data, pedigree_function=form.pedigree_function.data,
							age=form.age.data ,author=current_user, outcome=output)

		

		db.session.add(patient)
		db.session.commit()
		msg = Markup("Patient data has been added successfully, Prediction for added patient: <b><u>"+ word + "</u></b>")
		flash(msg, 'success')

		return redirect(url_for('main.view'))
	return render_template("create_patient.html", title="New Patient", form=form, legend = 'New Patient')


@patients.route("/patient/<int:patient_id>")
def patient(patient_id):
	patient = Patient.query.get_or_404(patient_id)
	return render_template('patient.html', title='Patient', patient=patient)


@patients.route("/patient/<int:patient_id>/update", methods=['GET','POST'])
@login_required
def update_patient(post_id):
	patient = Patient.query.get_or_404(patient_id)
	if patient.author != current_user:
		abort(403)
	form = PatientForm()
	if form.validate_on_submit():
		patient.pregnancies = form.pregnancies.data
		patient.glucose = form.glucose.data
		patient.bmi = form.bmi.data
		patient.pedigree_function = form.pedigree_function.data
		patient.age = form.age.data
		db.session.commit()
		flash('Patient data has been updated!', 'success')
		return redirect(url_for('patients.patient', patient_id=patient.id))
	elif request.method == 'GET':
		form.pregnancies.data = patient.pregnancies
		form.glucose.data = patient.glucose
		form.bmi.data = patient.bmi
		form.pedigree_function.data = patient.pedigree_function
		form.age.data = patient.age
	return render_template("create_patient.html", title="Update Patient", form = form, legend='Update Patient Data')


@patients.route("/patient/<int:patient_id>/delete", methods=['POST'])
@login_required
def delete_patient(patient_id):
	patient = Patient.query.get_or_404(patient_id)
	if patient.author != current_user:
		abort(403)
	db.session.delete(patient)
	db.session.commit()
	flash('Patient data been deleted','success')
	return redirect(url_for('main.home'))




diabetes_prediction_flaskapp/app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Patient
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, 
								ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created! You are now able to Log In', 'success')
		return redirect(url_for('users.login'))
	return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.view'))
		else:
			flash('Login Unsuccessful! Please try again', 'danger')

	return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('users.login'))

@users.route("/account" ,methods=['GET','POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.imagefile = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated', 'success')
		return redirect(url_for('users.account'))
	elif request.method =='GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	imagefile = url_for('static', filename='profile_pics/' + current_user.imagefile)
	return render_template("account.html", title="Account", imagefile=imagefile, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	patients = Patient.query.filter_by(author=user)\
		.order_by(Patient.date_posted.desc())\
		.paginate(page=page, per_page=5)
	return render_template('user_posts.html', patients=patients, user=user)


@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash("An email has been sent with instructions to reset your password.", 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been updated! You are now able to Log In', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title="Reset Password", form=form)

diabetes_prediction_flaskapp/app/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h1>About Page</h1>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ imagefile }}">
			<div class="media-body">
				<h2 class="account-heading">{{ current_user.username.upper() }}</h2>
				<p class="text-secondary">{{ current_user.email }}</p>
			</div>
		</div>
		<!--FORM HERE-->
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account Info</legend>
				
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
					
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class="form-control-file") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/create_patient.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>
				
				<div class="form-group">
					{{ form.pregnancies.label(class="form-control-label") }}
					
					{% if form.pregnancies.errors %}
						{{ form.pregnancies(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.pregnancies.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.pregnancies(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					{{ form.glucose.label(class="form-control-label") }}
					
					{% if form.glucose.errors %}
						{{ form.glucose(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.glucose.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.glucose(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.bmi.label(class="form-control-label") }}
					
					{% if form.bmi.errors %}
						{{ form.bmi(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.bmi.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.bmi(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.pedigree_function.label(class="form-control-label") }}
					
					{% if form.pedigree_function.errors %}
						{{ form.pedigree_function(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.pedigree_function.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.pedigree_function(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.age.label(class="form-control-label") }}
					
					{% if form.age.errors %}
						{{ form.age(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.age.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.age(class="form-control form-control-lg") }}
					{% endif %}

				</div>

			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/index.html
{% extends "layout.html" %}
<style type="text/css">
	 body, html {
    height: 100%;
}

/* The hero image */
.hero-image {
    /* Use "linear-gradient" to add a darken background effect to the image (photographer.jpg). This will make the text easier to read */
    background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("../profile_pic/medic.jpg");

    /* Set a specific height */
    height: 50%;

    /* Position and center the image to scale nicely on all screens */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    position: relative;
}

/* Place text in the middle of the image */
.hero-text {
    text-align: center;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    color: white;
}

</style>
{% block content %}
	  <div class="hero-image">
	  <div class="hero-text">
	    <h1><center>Welcome to the HealthApp</center></h1>
	    <p></p>
	    <center><a class="btn btn-lg btn-outline-info" href="{{ url_for('users.login') }}">Log In</a>&nbsp;&nbsp;&nbsp;<a href="{{ url_for('users.register') }}" class="btn btn-lg btn-outline-success">Sign Up</a></center>
	  </div>
	</div> 
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dataTables.bootstrap4.min.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>::Health-APP-{{ title }}</title>
	{% else %}
		<title>::Health-APP</title>
	{% endif %}
	<style type="text/css">
		body{
			
			zoom:90%;
		}
	</style>
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="/">Health APP</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						{% if current_user.is_authenticated %}
							
						{% else %}
							<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
						{% endif %}	
					
					</div>

					<!--navbar right side -->
					<div class="navbar-nav" id="side-stuff">
						{% if current_user.is_authenticated %}
							<a class="nav-item nav-link" href="{{ url_for('patients.new_patient') }}">New Patient</a>
							<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
							<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						{% else %}
							<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
							<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>

	
		<main role="main" class="container">
			<div class="row">
				<div class="col-md-12">
					{% with messages = get_flashed_messages(with_categories=true) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category}}">
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}

					{% block content %}{% endblock %}
				</div>
				
			</div>
		</main>
	

	

	
	<script src="{{ url_for('static', filename='jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='jquery-3.3.1.js') }}"></script>
	<script src="{{ url_for('static', filename='popper.min.js') }}"></script>
	<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='jquery.dataTables.min.js') }}"></script>
	<script src="{{ url_for('static', filename='dataTables.bootstrap4.min.js') }}"></script>

	<script type="text/javascript">
      $(document).ready(function() {
		    $('#mydata').DataTable();
		} );
    </script>
	
</body>
</html>

diabetes_prediction_flaskapp/app/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-check" style="padding-left: 3.5%;">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
				</small>
			</div>
		</form>
	</div>
	
	<div class="border-top pt-3">
		<small class="text-muted">
			Need an account?<a class="ml-2 " href="{{ url_for('users.register') }}">Sign Up Now</a>
		</small>
	</div>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/post.html
{% extends "layout.html" %}
{% block content %}
		<article class="media content-section">
			<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.imagefile ) }}">
			<div class="media-body">
				<div class="article-metadata">
					<a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username ) }}">{{ post.author.username.upper() }}</a>
					<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
					{% if post.author == current_user %}
						<div>
							<a class=" btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id ) }}">Update</a>
							<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
						</div>
					{% endif %}
				</div>
				<h2 class="article-title">{{ post.title }}</h2>
				<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
		<!--Modal-->
		<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<form action="{{ url_for('posts.delete_post', post_id=post.id ) }}" method="POST">
							<input type="submit" class="btn btn-danger" value="Delete">
						</form>
					</div>
				</div>
			</div>
		</div>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
					
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}

				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-nuted">
			Already have an account?<a class="ml-2 " href="{{ url_for('users.login') }}">Sign In</a>
		</small>
	</div>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<hr>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			
		</form>
	</div>
	<hr>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<hr>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}

				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			
		</form>
	</div>
	<hr>
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
	<h1 class="mb-3">Posts By {{ user.username.upper() }} ({{ posts.total }})</h1>
	{% for post in posts.items %}
		<article class="media content-section">
			<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.imagefile ) }}">
			<div class="media-body">
				<div class="article-metadata">
					<a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username ) }}">{{ post.author.username.upper() }}</a>
					<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
				<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock content %}

diabetes_prediction_flaskapp/app/templates/view.html
{% extends "layout.html" %}
{% block content %}
<table class="table table-hover table-bordered table-striped" id="mydata">
	<thead>
		<tr>
			<th>ID</th>
			<th>PREGNANCIES</th>
			<th>GLUCOSE</th>
			<th>BMI</th>
			<th>PEDIGREE FUNCTION</th>
			<th>AGE</th>
			<th>PREDICTED OUTCOME</th>
		</tr>
	</thead>
	<tbody>
	{% for patient in patients.items %}
		<tr>
			<td>{{ patient.id }}</td>
			<td>{{ patient.pregnancies }}</td>
			<td>{{ patient.glucose }}</td>
			<td>{{ patient.bmi }}</td>
			<td>{{ patient.pedigree_function }}</td>
			<td>{{ patient.age }}</td>
			<td>{{ patient.outcome }}</td>
		</tr>
	
	{% endfor %}
	</tbody>
</table>


{% endblock content %}